const mongoose = require('mongoose');


const Schema = mongoose.Schema;


const placeSchema = new Schema({
    //id to be autogenerated by mongoose
    title: { type: String, required: true },
    description: { type: String, required: true },
    image: { type: String, required: true },
    address: { type: String, required: true },
    location: {
        lat: { type: Number, required: true },
        lng: { type: Number, required: true }
    },
    //reference to the User document
    creator: { type: mongoose.Types.ObjectId, required: true, ref: 'User' },
});



module.exports = mongoose.model('Place', placeSchema);